#ifndef ZAD5MYLISTANDSORTING_DLASTUDENTOW_MYSORTING_H
#define ZAD5MYLISTANDSORTING_DLASTUDENTOW_MYSORTING_H

template <typename T>
void mySort(T);

#endif //ZAD5MYLISTANDSORTING_DLASTUDENTOW_MYSORTING_H
